-- USER: таблица зарезервирована в PG, используем кавычки по ТЗ
CREATE TABLE "user" (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(500) NOT NULL,
                        date_of_birth DATE NOT NULL, -- формат 01.05.1993 обрабатывается на уровне DTO
                        password VARCHAR(500) NOT NULL
);

CREATE TABLE account (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id BIGINT NOT NULL UNIQUE REFERENCES "user"(id), -- строго 1:1
                         balance DECIMAL(19,2) NOT NULL DEFAULT 0.00,
                         CONSTRAINT chk_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE email_data (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT NOT NULL REFERENCES "user"(id),
                            email VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE phone_data (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT NOT NULL REFERENCES "user"(id),
                            phone VARCHAR(13) NOT NULL UNIQUE -- формат 79207865432
);

-- Индексы для фильтрации (по ТЗ)
CREATE INDEX idx_user_dob ON "user"(date_of_birth);
CREATE INDEX idx_user_name ON "user"(name);
CREATE INDEX idx_email_unique ON email_data(email);
CREATE INDEX idx_phone_unique ON phone_data(phone);